# Generated by Django 3.1 on 2020-10-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
