# Generated by Django 3.1 on 2020-10-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_notice_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
