# Generated by Django 3.1 on 2020-12-04 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20201023_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'kategoria',
                'verbose_name_plural': 'kategorie',
                'ordering': ['symbol'],
            },
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-date', 'number'], 'verbose_name': 'zgłoszenie', 'verbose_name_plural': 'zgłoszenia'},
        ),
        migrations.AddField(
            model_name='notice',
            name='status',
            field=models.CharField(choices=[('n', 'nowy'), ('a', 'przyjęty'), ('d', 'wykonany'), ('r', 'odrzucony')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='notice',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='komentarz'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='number',
            field=models.CharField(help_text='max 16 znaków', max_length=16, unique=True, verbose_name='Numer'),
        ),
        migrations.AddField(
            model_name='notice',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notices', to='service.category', verbose_name='kategoria'),
        ),
    ]
