# Generated by Django 3.1 on 2021-01-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20201204_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='notice/', verbose_name='obraz'),
        ),
    ]
