# Generated by Django 3.1 on 2021-01-08 11:50

from django.db import migrations
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_notice_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='file',
            field=private_storage.fields.PrivateFileField(blank=True, default='', null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='notice/', verbose_name='plik'),
        ),
    ]
