# Generated by Django 3.1 on 2021-01-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_notice_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='user',
            field=models.TextField(blank=True, default='', verbose_name='stworzony przez'),
        ),
    ]
