# Generated by Django 3.1 on 2021-01-15 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0010_remove_notice_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='user',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.PROTECT, to='auth.user', verbose_name='user'),
            preserve_default=False,
        ),
    ]
